import { Injectable, Logger } from '@nestjs/common';
import { Connection } from 'typeorm';
import { User } from '../../entities/user';
import { Role } from '../../entities/role';

@Injectable()
export class UserSeeder {
  private readonly logger = new Logger(UserSeeder.name);

  constructor(private readonly connection: Connection) {}

  async run() {
    try {
      const userRepository = this.connection.getRepository(User);
      const roleRepository = this.connection.getRepository(Role);

      // Buscar los roles
      const adminRole = await roleRepository.findOne({ where: { name: 'Admin' } });
      const userRole = await roleRepository.findOne({ where: { name: 'User' } });

      if (!adminRole || !userRole) {
        throw new Error('Roles not found');
      }

      // Datos de ejemplo para el usuario admin
      const users = [
        {
          email: 'admin@example.com',
          password: 'securepassword', // Asegúrate de encriptar las contraseñas en producción
          name: 'Alice',
          lastname: 'Smith',
          Job: 'System Administrator',
          Curriculum: `Alice Smith es una Administradora de Sistemas con más de 10 años de experiencia en la gestión y mantenimiento de sistemas de TI en grandes corporaciones. Comenzó su carrera como Soporte Técnico en TechCorp, donde se especializó en la resolución de problemas y la implementación de soluciones de software personalizadas. Posteriormente, se unió a IT Solutions Ltd. como Administradora de Sistemas, donde lideró un equipo en la implementación de una nueva infraestructura de red y supervisó la actualización de los sistemas operativos y aplicaciones. Sus habilidades incluyen la administración de servidores, la seguridad de la red y la gestión de proyectos tecnológicos. Alice también ha sido reconocida por su capacidad para optimizar procesos y reducir costos operativos en un 15%.`,
          role: adminRole,
          roleId: adminRole.id,
        },
        // Datos de ejemplo para empleados
        {
          email: 'john.doe@example.com',
          password: 'securepassword',
          name: 'John',
          lastname: 'Doe',
          Job: 'Backend Developer',
          Curriculum: `John Doe es un Desarrollador Backend con 8 años de experiencia en la construcción de aplicaciones web robustas y escalables. Comenzó su carrera en CodeMasters como Desarrollador Junior, donde trabajó en el desarrollo de APIs RESTful y en la integración de bases de datos SQL. En su rol más reciente en DevHub, John ha liderado la creación de un sistema de gestión de usuarios utilizando Node.js y Express, implementando prácticas de DevOps y CI/CD para mejorar la eficiencia del ciclo de vida del desarrollo. John también tiene experiencia en la optimización de bases de datos y en la resolución de problemas de rendimiento. Sus habilidades en tecnologías como Docker y Kubernetes han sido cruciales para el éxito de proyectos importantes.`,
          role: userRole,
          roleId: userRole.id,
        },
        {
          email: 'jane.doe@example.com',
          password: 'securepassword',
          name: 'Jane',
          lastname: 'Doe',
          Job: 'UI/UX Designer',
          Curriculum: `Jane Doe es una Diseñadora UI/UX con 7 años de experiencia en la creación de interfaces intuitivas y atractivas para aplicaciones móviles y web. Su carrera comenzó en CreativeStudio, donde trabajó en el diseño de aplicaciones para clientes de alto perfil. En su rol actual en DesignWorks, Jane lidera el equipo de diseño en la creación de prototipos interactivos y en la realización de pruebas de usabilidad. Su experiencia incluye el trabajo con herramientas de diseño como Sketch y Figma, y ha implementado mejoras en la experiencia del usuario que han aumentado la satisfacción del cliente en un 25%. Jane también tiene un fuerte enfoque en la accesibilidad y la usabilidad, asegurando que los productos diseñados sean accesibles para todos los usuarios.`,
          role: userRole,
          roleId: userRole.id,
        },
        {
          email: 'michael.johnson@example.com',
          password: 'securepassword',
          name: 'Michael',
          lastname: 'Johnson',
          Job: 'Marketing Specialist',
          Curriculum: `Michael Johnson es un Especialista en Marketing con más de 6 años de experiencia en la creación e implementación de estrategias de marketing digital y tradicional. Empezó su carrera en AdVantage como Coordinador de Marketing, donde desarrolló campañas publicitarias exitosas que aumentaron el alcance de la marca en un 30%. En su puesto actual en MarketMakers, Michael dirige el equipo de marketing en el desarrollo de estrategias de contenido, gestión de redes sociales y análisis de datos para optimizar campañas publicitarias. Su enfoque analítico y su habilidad para identificar tendencias emergentes han sido clave para aumentar la participación del mercado en un 20% durante los últimos dos años.`,
          role: userRole,
          roleId: userRole.id,
        },
        {
          email: 'emily.clark@example.com',
          password: 'securepassword',
          name: 'Emily',
          lastname: 'Clark',
          Job: 'Project Manager',
          Curriculum: `Emily Clark es una Gerente de Proyectos con 9 años de experiencia en la gestión de proyectos complejos en la industria de TI. Comenzó su carrera en TechGlobal como Coordinadora de Proyectos y, con el tiempo, ascendió a Gerente de Proyectos en Global Solutions. Emily es experta en la planificación y ejecución de proyectos tecnológicos, coordinando equipos multifuncionales y gestionando presupuestos para asegurar el éxito del proyecto. Ha liderado proyectos significativos, incluyendo la implementación de un sistema ERP que redujo los costos operativos en un 20%. Sus habilidades incluyen la gestión de riesgos, la planificación estratégica y la comunicación efectiva con los interesados.`,
          role: userRole,
          roleId: userRole.id,
        },
        {
          email: 'daniel.williams@example.com',
          password: 'securepassword',
          name: 'Daniel',
          lastname: 'Williams',
          Job: 'Data Analyst',
          Curriculum: `Daniel Williams es un Analista de Datos con 5 años de experiencia en la recopilación, análisis e interpretación de datos complejos para tomar decisiones basadas en datos. Comenzó su carrera en Data Insights como Analista Junior y ha trabajado en varias empresas, incluida DataDriven, donde actualmente es el Analista Principal. Daniel es conocido por su habilidad para desarrollar informes detallados y visualizaciones de datos que ayudan a las empresas a identificar tendencias clave y oportunidades de mejora. Sus habilidades técnicas incluyen el uso de herramientas como Python, SQL y Tableau para el análisis y la visualización de datos. Daniel también tiene experiencia en la implementación de estrategias de análisis predictivo y en la mejora de procesos basados en datos.`,
          role: userRole,
          roleId: userRole.id,
        },
        {
          email: 'sophia.lopez@example.com',
          password: 'securepassword',
          name: 'Sophia',
          lastname: 'Lopez',
          Job: 'Frontend Developer',
          Curriculum: `Sophia Lopez es una Desarrolladora Frontend con 6 años de experiencia en la creación de interfaces de usuario dinámicas y receptivas. Comenzó su carrera en WebWorks como Desarrolladora Junior, donde trabajó en el desarrollo de sitios web y aplicaciones utilizando HTML, CSS y JavaScript. En su rol más reciente en CreativeTech, Sophia ha sido responsable del diseño y desarrollo de interfaces de usuario utilizando frameworks como React y Angular. Sus habilidades incluyen la optimización del rendimiento del frontend y la creación de experiencias de usuario fluidas. Sophia también ha trabajado en la integración de APIs y en la implementación de prácticas de desarrollo ágil en su equipo.`,
          role: userRole,
          roleId: userRole.id,
        },
        {
          email: 'james.brown@example.com',
          password: 'securepassword',
          name: 'James',
          lastname: 'Brown',
          Job: 'DevOps Engineer',
          Curriculum: `James Brown es un Ingeniero DevOps con 7 años de experiencia en la automatización y optimización de procesos de desarrollo y operaciones. Comenzó su carrera en BuildMaster como Ingeniero de Sistemas, donde trabajó en la configuración y gestión de servidores. En su rol actual en TechOps, James ha implementado soluciones de CI/CD utilizando Jenkins y GitLab, y ha trabajado en la migración de aplicaciones a entornos de contenedores utilizando Docker y Kubernetes. Sus habilidades incluyen la gestión de infraestructuras en la nube, la monitorización de sistemas y la implementación de prácticas de infraestructura como código. James ha sido clave en la reducción de tiempos de despliegue y en la mejora de la estabilidad del sistema.`,
          role: userRole,
          roleId: userRole.id,
        },
        {
          email: 'olivia.martin@example.com',
          password: 'securepassword',
          name: 'Olivia',
          lastname: 'Martin',
          Job: 'Human Resources Manager',
          Curriculum: `Olivia Martin es una Gerente de Recursos Humanos con más de 8 años de experiencia en la gestión de talento y desarrollo organizacional. Comenzó su carrera en PeopleFirst como Coordinadora de Recursos Humanos y ha trabajado en varias empresas, incluida TalentWorks, donde actualmente es la Gerente de Recursos Humanos. Olivia es experta en la implementación de políticas de recursos humanos, la gestión de relaciones laborales y el desarrollo de programas de formación y desarrollo. Ha liderado iniciativas para mejorar la retención de empleados y ha implementado programas de bienestar que han aumentado la satisfacción de los empleados en un 30%. Sus habilidades incluyen la gestión del cambio, la planificación de sucesiones y la resolución de conflictos.`,
          role: userRole,
          roleId: userRole.id,
        },
        {
          email: 'liam.miller@example.com',
          password: 'securepassword',
          name: 'Liam',
          lastname: 'Miller',
          Job: 'QA Engineer',
          Curriculum: `Liam Miller es un Ingeniero de QA con 5 años de experiencia en la realización de pruebas de software y aseguramiento de calidad. Comenzó su carrera en TestWorks como Analista de Pruebas y ha trabajado en varias empresas, incluida QualityTech, donde actualmente es Ingeniero de QA. Liam es experto en la creación y ejecución de planes de pruebas, la automatización de pruebas utilizando Selenium y la identificación de defectos en el software. Ha trabajado en estrecha colaboración con equipos de desarrollo para asegurar la calidad del producto y ha implementado mejoras en los procesos de pruebas que han reducido el número de defectos en un 40%. Sus habilidades incluyen la escritura de scripts de prueba, la creación de informes de pruebas y la colaboración en equipos multifuncionales.`,
          role: userRole,
          roleId: userRole.id,
        },
        {
          email: 'mia.davis@example.com',
          password: 'securepassword',
          name: 'Mia',
          lastname: 'Davis',
          Job: 'Business Analyst',
          Curriculum: `Mia Davis es una Analista de Negocios con 6 años de experiencia en la recopilación y análisis de requisitos empresariales para el desarrollo de soluciones tecnológicas. Comenzó su carrera en BizTech como Analista Junior y ha trabajado en varias empresas, incluida StrategyWorks, donde actualmente es Analista de Negocios. Mia es conocida por su habilidad para comunicarse con los interesados y traducir sus necesidades en especificaciones técnicas claras. Ha liderado proyectos de análisis de procesos y ha implementado soluciones que han mejorado la eficiencia operativa en un 25%. Sus habilidades incluyen el análisis de datos, la modelización de procesos de negocio y la gestión de proyectos. Mia también tiene experiencia en la creación de casos de uso y la facilitación de talleres de requisitos.`,
          role: userRole,
          roleId: userRole.id,
        },
        {
          email: 'lucas.white@example.com',
          password: 'securepassword',
          name: 'Lucas',
          lastname: 'White',
          Job: 'Network Engineer',
          Curriculum: `Lucas White es un Ingeniero de Redes con más de 8 años de experiencia en la gestión y configuración de infraestructuras de redes complejas. Comenzó su carrera en NetSolutions como Técnico de Redes, donde se especializó en la configuración de routers y switches Cisco. Actualmente trabaja en GlobalNet, donde lidera proyectos de expansión y optimización de redes, asegurando la seguridad y el rendimiento óptimo. Lucas tiene certificaciones como CCNA y CCNP y ha implementado soluciones de redes que han aumentado la eficiencia en un 30%.`,
          role: userRole,
          roleId: userRole.id,
        },
        {
          email: 'sara.lee@example.com',
          password: 'securepassword',
          name: 'Sara',
          lastname: 'Lee',
          Job: 'Product Manager',
          Curriculum: `Sara Lee es una Gerente de Producto con más de 10 años de experiencia en la gestión del ciclo de vida de productos tecnológicos. Empezó su carrera en Innovatech como Analista de Productos y ha trabajado en diversas empresas, incluida TechWare, donde actualmente es la Gerente de Producto. Sara ha liderado el desarrollo y lanzamiento de productos exitosos que han aumentado los ingresos en un 40%. Sus habilidades incluyen la planificación estratégica, el análisis de mercado y la gestión de equipos multifuncionales.`,
          role: userRole,
          roleId: userRole.id,
        },
        {
          email: 'robert.taylor@example.com',
          password: 'securepassword',
          name: 'Robert',
          lastname: 'Taylor',
          Job: 'Cybersecurity Specialist',
          Curriculum: `Robert Taylor es un Especialista en Ciberseguridad con 7 años de experiencia en la protección de sistemas y datos contra amenazas cibernéticas. Comenzó su carrera en SecureIT como Analista de Seguridad y ha trabajado en varias empresas, incluida SafeNet, donde actualmente es Especialista en Ciberseguridad. Robert es experto en la implementación de medidas de seguridad, la realización de auditorías y la respuesta a incidentes. Ha desarrollado estrategias de seguridad que han reducido los incidentes de seguridad en un 50%.`,
          role: userRole,
          roleId: userRole.id,
        },
        {
          email: 'victoria.evans@example.com',
          password: 'securepassword',
          name: 'Victoria',
          lastname: 'Evans',
          Job: 'Software Architect',
          Curriculum: `Victoria Evans es una Arquitecta de Software con más de 9 años de experiencia en el diseño y desarrollo de arquitecturas de software escalables. Comenzó su carrera en SoftDesign como Desarrolladora Senior y ha trabajado en varias empresas, incluida ArchiTech, donde actualmente es Arquitecta de Software. Victoria ha liderado el diseño de sistemas complejos y ha implementado soluciones arquitectónicas que han mejorado la eficiencia y escalabilidad de las aplicaciones. Sus habilidades incluyen el diseño de microservicios, la integración de sistemas y la optimización de procesos de desarrollo.`,
          role: userRole,
          roleId: userRole.id,
        },
        {
          email: 'mark.jones@example.com',
          password: 'securepassword',
          name: 'Mark',
          lastname: 'Jones',
          Job: 'Full Stack Developer',
          Curriculum: `Mark Jones es un Desarrollador Full Stack con 6 años de experiencia en el desarrollo de aplicaciones web completas. Empezó su carrera en WebBuilders como Desarrollador Frontend y ha trabajado en diversas empresas, incluida CodeBase, donde actualmente es Desarrollador Full Stack. Mark tiene experiencia en el desarrollo tanto del frontend como del backend de aplicaciones utilizando tecnologías como React, Node.js y MongoDB. Ha liderado proyectos que han mejorado la experiencia del usuario y la eficiencia del desarrollo en un 20%.`,
          role: userRole,
          roleId: userRole.id,
        },
        {
          email: 'emma.thomas@example.com',
          password: 'securepassword',
          name: 'Emma',
          lastname: 'Thomas',
          Job: 'Technical Writer',
          Curriculum: `Emma Thomas es una Escritora Técnica con más de 5 años de experiencia en la creación de documentación técnica clara y precisa. Comenzó su carrera en DocuTech como Redactora Técnica Junior y ha trabajado en varias empresas, incluida WritePro, donde actualmente es Escritora Técnica Principal. Emma ha desarrollado manuales de usuario, guías de instalación y documentación de API que han facilitado el uso de productos tecnológicos para usuarios y desarrolladores. Sus habilidades incluyen la redacción técnica, la edición y la creación de contenido gráfico. Ha mejorado la calidad de la documentación en un 30%.`,
          role: userRole,
          roleId: userRole.id,
        },
        {
          email: 'mason.harris@example.com',
          password: 'securepassword',
          name: 'Mason',
          lastname: 'Harris',
          Job: 'Data Scientist',
          Curriculum: `Mason Harris es un Científico de Datos con 7 años de experiencia en el análisis de grandes volúmenes de datos y el desarrollo de modelos predictivos. Empezó su carrera en DataAnalytics como Analista de Datos y ha trabajado en diversas empresas, incluida InsightData, donde actualmente es Científico de Datos Principal. Mason tiene experiencia en el uso de herramientas como Python, R y SQL para analizar datos y crear modelos que han mejorado la toma de decisiones en un 25%. Sus habilidades incluyen el aprendizaje automático, el análisis estadístico y la visualización de datos.`,
          role: userRole,
          roleId: userRole.id,
        },
        {
          email: 'amelia.moore@example.com',
          password: 'securepassword',
          name: 'Amelia',
          lastname: 'Moore',
          Job: 'Machine Learning Engineer',
          Curriculum: `Amelia Moore es una Ingeniera de Aprendizaje Automático con más de 6 años de experiencia en el desarrollo e implementación de algoritmos de machine learning. Comenzó su carrera en MLTech como Ingeniera de Software y ha trabajado en varias empresas, incluida AI Innovations, donde actualmente es Ingeniera de Aprendizaje Automático. Amelia ha creado modelos de aprendizaje automático que han mejorado la precisión de predicciones y la eficiencia operativa en un 20%. Sus habilidades incluyen el procesamiento de lenguaje natural, la visión por computadora y la optimización de modelos. Ha implementado soluciones que han permitido a las empresas tomar decisiones más informadas y basadas en datos.`,
          role: userRole,
          roleId: userRole.id,
        },
        {
          email: 'harper.jackson@example.com',
          password: 'securepassword',
          name: 'Harper',
          lastname: 'Jackson',
          Job: 'Mobile Developer',
          Curriculum: `Harper Jackson es una Desarrolladora de Aplicaciones Móviles con más de 5 años de experiencia en el desarrollo de aplicaciones nativas para iOS y Android. Comenzó su carrera en AppDev como Desarrolladora Junior y ha trabajado en varias empresas, incluida MobileMasters, donde actualmente es Desarrolladora de Aplicaciones Móviles Principal. Harper ha liderado proyectos de desarrollo de aplicaciones móviles que han mejorado la experiencia del usuario y la eficiencia operativa en un 25%. Sus habilidades incluyen el desarrollo en Swift, Kotlin y React Native. Ha implementado soluciones que han permitido a las empresas ofrecer experiencias móviles innovadoras y eficientes.`,
          role: userRole,
          roleId: userRole.id,
        },
        {
          email: 'jackson.king@example.com',
          password: 'securepassword',
          name: 'Jackson',
          lastname: 'King',
          Job: 'Cloud Architect',
          Curriculum: `Jackson King es un Arquitecto de Nube con más de 8 años de experiencia en el diseño e implementación de infraestructuras en la nube. Comenzó su carrera en CloudTech como Ingeniero de Sistemas y ha trabajado en varias empresas, incluida CloudSolutions, donde actualmente es Arquitecto de Nube Principal. Jackson ha liderado proyectos de migración a la nube que han mejorado la escalabilidad y la eficiencia operativa en un 30%. Sus habilidades incluyen la arquitectura de AWS, Azure y Google Cloud, y la implementación de soluciones de infraestructura como código. Ha implementado soluciones que han permitido a las empresas aprovechar al máximo las ventajas de la computación en la nube.`,
          role: userRole,
          roleId: userRole.id,
        },
        {
          email: 'lucas.white@example.com',
          password: 'securepassword',
          name: 'Lucas',
          lastname: 'White',
          Job: 'Network Engineer',
          Curriculum: `Lucas White es un Ingeniero de Redes con más de 8 años de experiencia en la gestión y configuración de infraestructuras de redes complejas. Comenzó su carrera en NetSolutions como Técnico de Redes, donde se especializó en la configuración de routers y switches Cisco. Actualmente trabaja en GlobalNet, donde lidera proyectos de expansión y optimización de redes, asegurando la seguridad y el rendimiento óptimo. Lucas tiene certificaciones como CCNA y CCNP y ha implementado soluciones de redes que han aumentado la eficiencia en un 30%.`,
          role: userRole,
          roleId: userRole.id,
        },
        {
          email: 'sara.lee@example.com',
          password: 'securepassword',
          name: 'Sara',
          lastname: 'Lee',
          Job: 'Product Manager',
          Curriculum: `Sara Lee es una Gerente de Producto con más de 10 años de experiencia en la gestión del ciclo de vida de productos tecnológicos. Empezó su carrera en Innovatech como Analista de Productos y ha trabajado en diversas empresas, incluida TechWare, donde actualmente es la Gerente de Producto. Sara ha liderado el desarrollo y lanzamiento de productos exitosos que han aumentado los ingresos en un 40%. Sus habilidades incluyen la planificación estratégica, el análisis de mercado y la gestión de equipos multifuncionales.`,
          role: userRole,
          roleId: userRole.id,
        },
        {
          email: 'robert.taylor@example.com',
          password: 'securepassword',
          name: 'Robert',
          lastname: 'Taylor',
          Job: 'Cybersecurity Specialist',
          Curriculum: `Robert Taylor es un Especialista en Ciberseguridad con 7 años de experiencia en la protección de sistemas y datos contra amenazas cibernéticas. Comenzó su carrera en SecureIT como Analista de Seguridad y ha trabajado en varias empresas, incluida SafeNet, donde actualmente es Especialista en Ciberseguridad. Robert es experto en la implementación de medidas de seguridad, la realización de auditorías y la respuesta a incidentes. Ha desarrollado estrategias de seguridad que han reducido los incidentes de seguridad en un 50%.`,
          role: userRole,
          roleId: userRole.id,
        },
        {
          email: 'victoria.evans@example.com',
          password: 'securepassword',
          name: 'Victoria',
          lastname: 'Evans',
          Job: 'Software Architect',
          Curriculum: `Victoria Evans es una Arquitecta de Software con más de 9 años de experiencia en el diseño y desarrollo de arquitecturas de software escalables. Comenzó su carrera en SoftDesign como Desarrolladora Senior y ha trabajado en varias empresas, incluida ArchiTech, donde actualmente es Arquitecta de Software. Victoria ha liderado el diseño de sistemas complejos y ha implementado soluciones arquitectónicas que han mejorado la eficiencia y escalabilidad de las aplicaciones. Sus habilidades incluyen el diseño de microservicios, la integración de sistemas y la optimización de procesos de desarrollo.`,
          role: userRole,
          roleId: userRole.id,
        },
        {
          email: 'mark.jones@example.com',
          password: 'securepassword',
          name: 'Mark',
          lastname: 'Jones',
          Job: 'Full Stack Developer',
          Curriculum: `Mark Jones es un Desarrollador Full Stack con 6 años de experiencia en el desarrollo de aplicaciones web completas. Empezó su carrera en WebBuilders como Desarrollador Frontend y ha trabajado en diversas empresas, incluida CodeBase, donde actualmente es Desarrollador Full Stack. Mark tiene experiencia en el desarrollo tanto del frontend como del backend de aplicaciones utilizando tecnologías como React, Node.js y MongoDB. Ha liderado proyectos que han mejorado la experiencia del usuario y la eficiencia del desarrollo en un 20%.`,
          role: userRole,
          roleId: userRole.id,
        },
        {
          email: 'emma.thomas@example.com',
          password: 'securepassword',
          name: 'Emma',
          lastname: 'Thomas',
          Job: 'Technical Writer',
          Curriculum: `Emma Thomas es una Escritora Técnica con más de 5 años de experiencia en la creación de documentación técnica clara y precisa. Comenzó su carrera en DocuTech como Redactora Técnica Junior y ha trabajado en varias empresas, incluida WritePro, donde actualmente es Escritora Técnica Principal. Emma ha desarrollado manuales de usuario, guías de instalación y documentación de API que han facilitado el uso de productos tecnológicos para usuarios y desarrolladores. Sus habilidades incluyen la redacción técnica, la edición y la creación de contenido gráfico. Ha mejorado la calidad de la documentación en un 30%.`,
          role: userRole,
          roleId: userRole.id,
        },
        {
          email: 'mason.harris@example.com',
          password: 'securepassword',
          name: 'Mason',
          lastname: 'Harris',
          Job: 'Data Scientist',
          Curriculum: `Mason Harris es un Científico de Datos con 7 años de experiencia en el análisis de grandes volúmenes de datos y el desarrollo de modelos predictivos. Empezó su carrera en DataAnalytics como Analista de Datos y ha trabajado en diversas empresas, incluida InsightData, donde actualmente es Científico de Datos Principal. Mason tiene experiencia en el uso de herramientas como Python, R y SQL para analizar datos y crear modelos que han mejorado la toma de decisiones en un 25%. Sus habilidades incluyen el aprendizaje automático, el análisis estadístico y la visualización de datos.`,
          role: userRole,
          roleId: userRole.id,
        },
        {
          email: 'amelia.moore@example.com',
          password: 'securepassword',
          name: 'Amelia',
          lastname: 'Moore',
          Job: 'Machine Learning Engineer',
          Curriculum: `Amelia Moore es una Ingeniera de Aprendizaje Automático con más de 6 años de experiencia en el desarrollo e implementación de algoritmos de machine learning. Comenzó su carrera en MLTech como Ingeniera de Software y ha trabajado en varias empresas, incluida AI Innovations, donde actualmente es Ingeniera de Aprendizaje Automático. Amelia ha creado modelos de aprendizaje automático que han mejorado la precisión de predicciones y la eficiencia operativa en un 20%. Sus habilidades incluyen el procesamiento de lenguaje natural, la visión por computadora y la optimización de modelos. Ha implementado soluciones que han permitido a las empresas tomar decisiones más informadas y basadas en datos.`,
          role: userRole,
          roleId: userRole.id,
        },
        {
          email: 'harper.jackson@example.com',
          password: 'securepassword',
          name: 'Harper',
          lastname: 'Jackson',
          Job: 'Mobile Developer',
          Curriculum: `Harper Jackson es una Desarrolladora de Aplicaciones Móviles con más de 5 años de experiencia en el desarrollo de aplicaciones nativas para iOS y Android. Comenzó su carrera en AppDev como Desarrolladora Junior y ha trabajado en varias empresas, incluida MobileMasters, donde actualmente es Desarrolladora de Aplicaciones Móviles Principal. Harper ha liderado proyectos de desarrollo de aplicaciones móviles que han mejorado la experiencia del usuario y la eficiencia operativa en un 25%. Sus habilidades incluyen el desarrollo en Swift, Kotlin y React Native. Ha implementado soluciones que han permitido a las empresas ofrecer experiencias móviles innovadoras y eficientes.`,
          role: userRole,
          roleId: userRole.id,
        },
        {
          email: 'jackson.king@example.com',
          password: 'securepassword',
          name: 'Jackson',
          lastname: 'King',
          Job: 'Cloud Architect',
          Curriculum: `Jackson King es un Arquitecto de Nube con más de 8 años de experiencia en el diseño e implementación de infraestructuras en la nube. Comenzó su carrera en CloudTech como Ingeniero de Sistemas y ha trabajado en varias empresas, incluida CloudSolutions, donde actualmente es Arquitecto de Nube Principal. Jackson ha liderado proyectos de migración a la nube que han mejorado la escalabilidad y la eficiencia operativa en un 30%. Sus habilidades incluyen la arquitectura de AWS, Azure y Google Cloud, y la implementación de soluciones de infraestructura como código. Ha implementado soluciones que han permitido a las empresas aprovechar al máximo las ventajas de la computación en la nube.`,
          role: userRole,
          roleId: userRole.id,
        },
        {
          email: 'chloe.green@example.com',
          password: 'securepassword',
          name: 'Chloe',
          lastname: 'Green',
          Job: 'HR Manager',
          Curriculum: `Chloe Green es una Gerente de Recursos Humanos con más de 9 años de experiencia en la gestión de talento y desarrollo organizacional. Comenzó su carrera en PeopleFirst como Coordinadora de Recursos Humanos y ha trabajado en varias empresas, incluida TalentWorks, donde actualmente es Gerente de Recursos Humanos. Chloe ha implementado programas de desarrollo de liderazgo y ha mejorado las políticas de retención de empleados, reduciendo la rotación en un 20%. Sus habilidades incluyen la gestión del talento, el desarrollo de políticas de recursos humanos y la mediación de conflictos.`,
          role: userRole,
          roleId: userRole.id,
        },
        {
          email: 'oliver.brown@example.com',
          password: 'securepassword',
          name: 'Oliver',
          lastname: 'Brown',
          Job: 'DevOps Engineer',
          Curriculum: `Oliver Brown es un Ingeniero DevOps con más de 6 años de experiencia en la implementación de prácticas de integración y entrega continua. Comenzó su carrera en BuildMasters como Ingeniero de Sistemas y ha trabajado en varias empresas, incluida DevOpsWorks, donde actualmente es Ingeniero DevOps Principal. Oliver ha optimizado pipelines de CI/CD y ha mejorado la eficiencia del desarrollo en un 25%. Sus habilidades incluyen la automatización de infraestructura, el monitoreo y la gestión de configuraciones utilizando herramientas como Jenkins, Docker y Kubernetes.`,
          role: userRole,
          roleId: userRole.id,
        },
        {
          email: 'sophia.martin@example.com',
          password: 'securepassword',
          name: 'Sophia',
          lastname: 'Martin',
          Job: 'UX/UI Designer',
          Curriculum: `Sophia Martin es una Diseñadora UX/UI con más de 5 años de experiencia en la creación de experiencias de usuario intuitivas y atractivas. Comenzó su carrera en DesignCo como Diseñadora Junior y ha trabajado en varias empresas, incluida UserFirst, donde actualmente es Diseñadora UX/UI Principal. Sophia ha liderado proyectos de rediseño de aplicaciones que han mejorado la satisfacción del usuario en un 30%. Sus habilidades incluyen el diseño centrado en el usuario, la creación de wireframes y prototipos, y la realización de pruebas de usabilidad.`,
          role: userRole,
          roleId: userRole.id,
        },
        {
          email: 'liam.carter@example.com',
          password: 'securepassword',
          name: 'Liam',
          lastname: 'Carter',
          Job: 'IT Support Specialist',
          Curriculum: `Liam Carter es un Especialista en Soporte IT con más de 4 años de experiencia en la resolución de problemas técnicos y el soporte al usuario. Comenzó su carrera en HelpDesk Solutions como Técnico de Soporte y ha trabajado en varias empresas, incluida TechAssist, donde actualmente es Especialista en Soporte IT. Liam ha mejorado la satisfacción del usuario y ha reducido los tiempos de resolución de problemas en un 20%. Sus habilidades incluyen la resolución de problemas de hardware y software, la gestión de tickets y el soporte remoto.`,
          role: userRole,
          roleId: userRole.id,
        },
        {
          email: 'ava.wilson@example.com',
          password: 'securepassword',
          name: 'Ava',
          lastname: 'Wilson',
          Job: 'Data Analyst',
          Curriculum: `Ava Wilson es una Analista de Datos con más de 5 años de experiencia en el análisis e interpretación de datos para la toma de decisiones empresariales. Comenzó su carrera en DataWorks como Analista de Datos Junior y ha trabajado en varias empresas, incluida InsightAnalytics, donde actualmente es Analista de Datos Principal. Ava ha desarrollado dashboards y reportes que han mejorado la eficiencia operativa en un 15%. Sus habilidades incluyen el análisis de datos, la creación de visualizaciones y la programación en SQL y Python.`,
          role: userRole,
          roleId: userRole.id,
        },
        {
          email: 'james.thompson@example.com',
          password: 'securepassword',
          name: 'James',
          lastname: 'Thompson',
          Job: 'Project Manager',
          Curriculum: `James Thompson es un Gerente de Proyectos con más de 7 años de experiencia en la gestión de proyectos tecnológicos. Comenzó su carrera en TechProjects como Coordinador de Proyectos y ha trabajado en varias empresas, incluida ProManage, donde actualmente es Gerente de Proyectos. James ha liderado proyectos de desarrollo e implementación que han mejorado la eficiencia y los tiempos de entrega en un 25%. Sus habilidades incluyen la planificación de proyectos, la gestión de recursos y la comunicación con stakeholders.`,
          role: userRole,
          roleId: userRole.id,
        },
        {
          email: 'mia.miller@example.com',
          password: 'securepassword',
          name: 'Mia',
          lastname: 'Miller',
          Job: 'SEO Specialist',
          Curriculum: `Mia Miller es una Especialista en SEO con más de 6 años de experiencia en la optimización de sitios web para motores de búsqueda. Comenzó su carrera en WebOptimize como Analista SEO y ha trabajado en varias empresas, incluida SearchMasters, donde actualmente es Especialista en SEO Principal. Mia ha mejorado el posicionamiento en los resultados de búsqueda y ha aumentado el tráfico orgánico en un 35%. Sus habilidades incluyen la investigación de palabras clave, la optimización on-page y off-page, y la creación de contenido.`,
          role: userRole,
          roleId: userRole.id,
        },
        {
          email: 'william.morris@example.com',
          password: 'securepassword',
          name: 'William',
          lastname: 'Morris',
          Job: 'Quality Assurance Engineer',
          Curriculum: `William Morris es un Ingeniero de Aseguramiento de la Calidad con más de 8 años de experiencia en la realización de pruebas y aseguramiento de la calidad de software. Comenzó su carrera en TestIt como Analista de QA y ha trabajado en varias empresas, incluida QualityFirst, donde actualmente es Ingeniero de QA Principal. William ha implementado estrategias de prueba que han mejorado la calidad del software y reducido los errores en un 30%. Sus habilidades incluyen la creación de casos de prueba, la automatización de pruebas y la realización de pruebas de regresión.`,
          role: userRole,
          roleId: userRole.id,
        },
        {
          email: 'sophia.james@example.com',
          password: 'securepassword',
          name: 'Sophia',
          lastname: 'James',
          Job: 'Marketing Manager',
          Curriculum: `Sophia James es una Gerente de Marketing con más de 9 años de experiencia en la planificación y ejecución de campañas de marketing. Comenzó su carrera en MarketPro como Coordinadora de Marketing y ha trabajado en varias empresas, incluida BrandBoost, donde actualmente es Gerente de Marketing. Sophia ha liderado campañas que han aumentado la visibilidad de la marca y los ingresos en un 40%. Sus habilidades incluyen la planificación estratégica, la gestión de campañas digitales y la análisis de mercado.`,
          role: userRole,
          roleId: userRole.id,
        },
        {
          email: 'logan.walker@example.com',
          password: 'securepassword',
          name: 'Logan',
          lastname: 'Walker',
          Job: 'Systems Administrator',
          Curriculum: `Logan Walker es un Administrador de Sistemas con más de 7 años de experiencia en la gestión y mantenimiento de infraestructuras de TI. Comenzó su carrera en SysAdmin Solutions como Técnico de Soporte y ha trabajado en varias empresas, incluida ITSupport, donde actualmente es Administrador de Sistemas Principal. Logan ha mejorado la eficiencia operativa y ha reducido el tiempo de inactividad en un 25%. Sus habilidades incluyen la gestión de servidores, la administración de redes y la virtualización.`,
          role: userRole,
          roleId: userRole.id,
        },
        {
          email: 'isabella.anderson@example.com',
          password: 'securepassword',
          name: 'Isabella',
          lastname: 'Anderson',
          Job: 'Content Strategist',
          Curriculum: `Isabella Anderson es una Estratega de Contenido con más de 5 años de experiencia en la creación y gestión de estrategias de contenido. Comenzó su carrera en ContentCreators como Redactora de Contenidos y ha trabajado en varias empresas, incluida ContentMaster, donde actualmente es Estratega de Contenidos. Isabella ha desarrollado estrategias de contenido que han aumentado el engagement y la visibilidad en un 30%. Sus habilidades incluyen la redacción, la creación de calendarios de contenido y la optimización de contenido para SEO.`,
          role: userRole,
          roleId: userRole.id,
        },
      ];

      for (const userData of users) {
        const user = userRepository.create(userData);
        await userRepository.save(user);
        this.logger.log(`Seeded user: ${user.email} with role: ${user.role}`);
      }
    } catch (error) {
      this.logger.error(`Failed to seed users: ${error.message}`, error.stack);
    }
  }
}
